simple-icons/simple-icons-font

.travis.yml

As a basic test for Pull Requests to verify that at least the build script works. You can view the first build [right here](https://travis-ci.com/simple-icons/simple-icons-font/builds/119267354) 😄 
---
<sup>Also changed indentation from tabs to spaces</sup>

Add Continuous Integration job to build the font

---

.travis.yml
package-lock.json
package.json

Audited the dependencies for this project using `$ npm audit fix`, tested if everything still works using `$ npm run build:testpage` and it looked good 👌

Audit dependencies

---

package-lock.json
package.json

See: 
- [v1.15.0](https://github.com/simple-icons/simple-icons/pull/1617)
- [v1.16.0](https://github.com/simple-icons/simple-icons/pull/1634)
- [v1.17.0](https://github.com/simple-icons/simple-icons/pull/1701)

Update simple-icons to v1.17.1

---

package-lock.json
package.json
scripts/build.js

Generate minified CSS at build process

---

.github/workflows/publish.yml
.github/workflows/verify.yml
README.md
package-lock.json
package.json

_The new version of the package will be v2.0.0_
- Add _Setup_  and _Usage_ documentation.

Release v2.0.1

---

.github/workflows/auto-release.yml
.github/workflows/publish.yml
.github/workflows/verify.yml
.gitignore
README.md
package-lock.json
package.json
scripts/preview.js

_The new version of the package will be v2.19.0_
- Update `simple-icons` to v2.19.0 ( #60)
- Fix error in usage documentation (#59)

Release v2.19.0

---

.editorconfig
.gitattributes
CONTRIBUTING.md
README.md
package-lock.json
package.json

_The new version of the package will be v3.13.1_
- (Re)add colorless example to the Usage section (#66)

Release v3.13.1

---

README.md
package-lock.json
package.json

_The new version of the package will be v4.0.0_
- Update `simple-icons` to v4.0.0 (#65)

Release v4.0.0

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/font.md
CONTRIBUTING.md
package-lock.json
package.json

_The new version of the package will be v4.1.0_
- Update `simple-icons` to v4.1.0 (#72)

Release v4.1.0

---

.editorconfig
.github/ISSUE_TEMPLATE/config.yml
.github/renovate.json5
.github/workflows/auto-release.yml
.github/workflows/publish.yml
.github/workflows/verify.yml
.prettierignore
package-lock.json
package.json
preview/assets/script.js
preview/assets/style.css
preview/css/base.css
preview/html/testpage.pug
scripts/build-testpage.js
scripts/build.js
scripts/preview.js
scripts/version.js

_The new version of the package will be v4.2.0_
- Update `simple-icons` to v4.2.0 (#75)

Release v4.2.0

---

package-lock.json
package.json

_The new version of the package will be v4.3.0_
- Update `simple-icons` to v4.3.0 (#78)

Release v4.3.0

---

package-lock.json
package.json

_The new version of the package will be v4.4.0_
- Update `simple-icons` to v4.4.0 (#80)

Release v4.4.0

---

package-lock.json
package.json

_The new version of the package will be v4.5.0_
- Update `simple-icons` to v4.5.0 (#82)

Release v4.5.0

---

.github/renovate.json5
.gitignore
.prettierignore
package-lock.json
package.json
scripts/build-testpage.js
scripts/build.js
scripts/bump-version.js
scripts/preview.js

_The new version of the package will be v4.6.1_
- Remove `postinstall` script from package (#94)

Release v4.6.1

---

package-lock.json
package.json
scripts/build.js
scripts/templates/base.css

Tested manually in Internet Explorer 11 and works as expected.

Implement EOT font building

---

package-lock.json
package.json
scripts/build.js
scripts/templates/base.css

I've ported a package from Python that converts from WOFF to OTF. Tested locally and works as expected. Closes #49

Implement OTF font building

---

package.json

Replace 'postinstall' script for husky by 'prepare'

---

.github/FUNDING.yml

Add Open Collective link to Simple-Icons-Font.

Add Open Collective

---

README.md

Adds a link in the README to the Disclaimer.md file in the main repo.

Add Disclaimer Link

---

scripts/build.js

- Update build script for fonts to use `.Get` (https://github.com/simple-icons/simple-icons/pull/5777)
_More suggestions for improvements to the script are welcome_

Update build scripts

---

.github/renovate.json5

Issue: #132 (it will be automatically closed by @renovate-bot spammer 😆 ).

Disable Renovate dependency dashboard

---

.github/workflows/auto-release.yml

The same as here: https://github.com/simple-icons/simple-icons-website/pull/155

Pin to NodeJS v12 in "Automated Releases" CI workflow

---

composer.json

Following from https://github.com/simple-icons/simple-icons/pull/7219

Add `funding` key to composer.json

---

composer.json

Following from https://github.com/simple-icons/simple-icons/pull/7382

Add links to `composer.json`

---

preview/html/testpage.pug
scripts/build-testpage.js
scripts/build.js

`.Get` property has been deprecated in v7.

Update syntax for v7

---

preview/assets/style.css
preview/html/testpage.pug
scripts/templates/base.css

Add `vertical-align: middle` to default style reset

---

.github/workflows/auto-release.yml
.github/workflows/publish.yml
.github/workflows/verify.yml

Following from https://github.com/simple-icons/simple-icons-website/pull/230, it has been proved a functional configuration.

Add permissions to CI workflows

---

.github/workflows/publish.yml
.gitignore

Include fonts as assets in releases

---

README.md

Following from https://github.com/simple-icons/simple-icons/pull/8148

Fix CI tests state badge of README

---

.github/workflows/publish.yml

Add `font/` folder to releases

---

.github/workflows/publish.yml

Stop using `mondeja/strip-gh-theme-links` action

---

.github/renovate.json5
.github/workflows/renovate.yml

Following from https://github.com/simple-icons/simple-icons/pull/10621

Configure self hosted Renovate

---

.github/renovate.json5

To prevent this error: https://github.com/simple-icons/simple-icons-font/actions/runs/9068777274/job/24916834350#step:5:161

Add `repositories` field to Renovate config

---

.github/workflows/auto-release.yml

Our simple-icons-font has several versions left behind.
Broken CI: https://github.com/simple-icons/simple-icons-font/actions/runs/9143691036/job/25140686544

Use GitHub Token for auto-release

---

.github/renovate.json5

Following from https://github.com/simple-icons/simple-icons/pull/12150 and https://github.com/simple-icons/simple-icons/pull/12104

Fix error and improve title of Renovate PR

---

.github/workflows/publish.yml

Documentation: [docs.npmjs.com/generating-provenance-statements](https://docs.npmjs.com/generating-provenance-statements)

Generate provenance statements when publishing

---

.github/workflows/auto-release.yml

Add cron job as fallback for automated releases

---

.github/workflows/auto-release.yml

Use `simple-icons[bot]` for "Bump version" commits
