package-lock.json
package.json
scripts/build.js

Updates Simple Icons from v1.9.25 to v1.11.0
---
I had to remove the Elsevier logo from the font as it seems to be too large for fonts.`icon-font-buildr` gives the following ⬇️ error when building **with** the Elsevier logo.
```
events.js:167
throw er; // Unhandled 'error' event
^
Error: Max buffer length exceeded: attribValue
Line: 0
Column: 130705
Char:
at error (D:\Workspace\simple-icons-font\node_modules\sax\lib\sax.js:651:10)
at checkBufferLength (D:\Workspace\simple-icons-font\node_modules\sax\lib\sax.js:125:13)
at SAXParser.write (D:\Workspace\simple-icons-font\node_modules\sax\lib\sax.js:1505:7)
at SAXStream.write (D:\Workspace\simple-icons-font\node_modules\sax\lib\sax.js:239:18)
at ReadStream.ondata (_stream_readable.js:666:20)
at ReadStream.emit (events.js:182:13)
at addChunk …
```

Update Simple Icons dependency

---

package-lock.json
package.json
scripts/build.js

This Pull Request updates Simple Icons to the latest version. See https://github.com/simple-icons/simple-icons/pull/1549 for details.
Due to a change in the API I had to implement a bit of a hack to circumvent a problem with iterating over all the icons. ~~I will be addressing this issue up-stream 👍 EDIT: see https://github.com/simple-icons/simple-icons/issues/1554~~ This has been fixed and we should remove the hack when upgrading to the next version of Simple Icons.

Update Simple Icons to v1.14.0

---

package-lock.json
package.json

Run a local server with `$ npm test` script using [anywhere](https://www.npmjs.com/package/anywhere). This automatically builds the test page (`$ npm run build:testpage`) and opens it for you in a locally run server (I intentionally set the host to `localhost`).

Run local server with test script

---

.svgo.yml
package-lock.json
package.json
scripts/build.js
scripts/svgo.js

This updates the `simple-icons` dependency to the latest version (`v1.17.1` to `v2.3.0`). In addition it resolves the build problems described in #29.

Update Simple Icons to the latest version

---

scripts/build.js

Closes #46
WOFF fonts metadata are built from TFF, so is enough by defining it inside the TTF file. The version must be in that format, seems that is the standarized way of define it for TTF.
I've tested it with Ubuntu Typographies.

Customize generated fonts metadata

---

.github/workflows/publish.yml

The build process it's executed 2 times in publish workflow, one explicitly and implicitly with `prepublishOnly` script.
I've removed the explicit step in this pull. Other option is to remove the `prepublishOnly` script.

Build in publish workflow using 'prepublishOnly' script

---

README.md

Closes #5
- Setup instructions with example using the font from CDN.
- Setup instructions with example downloading the font from NPM registry. The URL has the version hardcoded, this must be updated by release process or find a way to reference the latest version.
- Installation for module bundlers.
- Basic description of CSS classes.
- Improved badges images and README Markdown markup.

Add setup and usage documentation to README

---

.github/workflows/publish.yml
README.md

As per https://github.com/simple-icons/simple-icons-font/pull/53#discussion_r544604289, this updates the `publish.yml` workflow to automatically create git tags and GitHub Releases for every release. The configuration is based on [the same job for the main repo](https://github.com/simple-icons/simple-icons/blob/c6044cf0c74a6e5a9a92dac3c426c5643b5790d4/.github/workflows/publish.yml#L28-L73), but slightly simplified as I didn't try to come up with a fancy release title or body. I'd say, if we want, we can come up with some content for the release later.

Set up automated GitHub releases

---

README.md

The classname we used to apply color to font icons in the README was incorrect, so I changed it from `simple-icons--color` to `simpleicons--color`.
This is arguably superceded by #58, but I would like to include this change before the breaking change.

Fix color modifier classname in README Usage

---

package-lock.json
package.json

Following the planning discussed in #50 this is in preparation of the next release, v2.19.0, which will match [simple-icons@2.19.0](https://www.npmjs.com/package/simple-icons/v/2.19.0).

Update simple-icons dependency to v2.19.0

---

package-lock.json
package.json

Following the planning discussed in #50 this is in preparation of the next release, v3.13.0, which will match [simple-icons@3.13.0](https://www.npmjs.com/package/simple-icons/v/3.13.0).
* * *
_Since simple-icons removed a number of icons in the release from v2.19.0 to v3.0.0 this is a breaking change, as those icons are also removed from the font._

Update simple-icons dependency to v3.13.0

---

.editorconfig
.gitattributes
CONTRIBUTING.md
README.md

- Updates `.gitattributes` to be more similar to [the `.gitattributes` of the main project](https://github.com/simple-icons/simple-icons/blob/fa85d6e9b52f8521738e967c833bb53e1e6ad1bb/.gitattributes).
- Add an `.editorconfig` file, similar to [the `.editorconfig` file of the main project](https://github.com/simple-icons/simple-icons/blob/fa85d6e9b52f8521738e967c833bb53e1e6ad1bb/.editorconfig).
- Update the Contributing Guidelines (feedback welcome).
- Re-add the colorless example in the README's usage section (that I accidentally removed in #58). @mondeja should we release a patch of [v3.13.0](https://www.npmjs.com/package/simple-icons-font/v/3.13.0) with updated documentation?

Minor repository improvements

---

package-lock.json
package.json

Following the planning discussed in #50 this is in preparation of the next release, v4.0.0, which will match [simple-icons@4.0.0](https://www.npmjs.com/package/simple-icons/v/4.0.0).
* * *
_Since simple-icons [removed a number of icons](https://github.com/simple-icons/simple-icons/milestone/3?closed=1) in the release from v3.13.0 to v4.0.0 this is a breaking change, as those icons are also removed from the font._

Update simple-icons dependency to v4.0.0

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/font.md
CONTRIBUTING.md

This adds definitions for issue templates (mostly just references to the issue templates of the main project), similar to what can be seen at https://github.com/ericcornelissen/simple-icons-website/issues/new/choose. I'm not 100% sure about the link to the packages issue in `config.yml`... :thinking: 
Also, it adds a link to the Contributing Guidelines for people to request new icons, thought that may be useful but I would be happy to remove it.

Add issue templates (+ minor change to CONTRIBUTING.md)

---

package-lock.json
package.json

Following the planning discussed in #50 this is in preparation of the next release, v4.1.0, which will match [simple-icons@4.1.0](https://www.npmjs.com/package/simple-icons/v/4.1.0).
* * *
<sup>I intentionally skipped release [simple-icons@v4.0.1](https://github.com/simple-icons/simple-icons/releases/tag/4.0.1) because it doesn't add or update any icon</sup>

Update simple-icons dependency to v4.1.0

---

package-lock.json
package.json

Following the planning discussed in #50 this is in preparation of the next release, v4.2.0, which will match [simple-icons@4.2.0](https://www.npmjs.com/package/simple-icons/v/4.2.0).

 Update simple-icons dependency to v4.2.0

---

package-lock.json
package.json

Following the planning discussed in #50 this is in preparation of the next release, v4.3.0, which will match [simple-icons@4.3.0](https://www.npmjs.com/package/simple-icons/v/4.3.0).

Update simple-icons dependency to v4.3.0

---

package-lock.json
package.json

Following the planning discussed in #50 this is in preparation of the next release, v4.4.0, which will match [simple-icons@4.4.0](https://www.npmjs.com/package/simple-icons/v/4.4.0).

Update simple-icons dependency to v4.4.0

---

package-lock.json
package.json

Following the planning discussed in #50 this is in preparation of the next release, v4.5.0, which will match [simple-icons@4.5.0](https://www.npmjs.com/package/simple-icons/v/4.5.0).
<sup>And then we are finally caught up with [the main repo](https://github.com/simple-icons/simple-icons) :tada:</sup>

Update simple-icons dependency to v4.5.0

---

scripts/build-testpage.js
scripts/build.js
scripts/bump-version.js
scripts/preview.js

Based on [this comment](https://github.com/simple-icons/simple-icons-font/pull/77#pullrequestreview-564431254) and the practice of adding `@fileoverview`s at the top of scripts in the main repo (e.g. [in `build-package.js`](https://github.com/simple-icons/simple-icons/blob/9e09db732429c9d2526d7fb297f1183013875b9c/scripts/build-package.js#L1-L8), this adds an `@fileoverview` to every script in this project as well.

Add at-fileoverviews for scripts

---

scripts/build.js

The change is minimal. For some reason I added the library in #45 but used the NodeJS builtin version of the library. The instructions for updating are [here](https://github.com/bestiejs/punycode.js#installation).
Closes #88

Use 'punycode/' require to import the userland module

---

.github/renovate.json5

Following the general idea of [the configuration of Renovate in the main repo](https://github.com/simple-icons/simple-icons/blob/develop/.github/renovate.json5), this updates the Renovate configuration to run on a schedule and to group changes into a single PR.
With #1 closed and development mostly done, I figured we don't need updates as soon as they're available anymore. Arguably we can change the schedule to run even less.

Update Renovate configuration

---

scripts/build-testpage.js
scripts/build.js
scripts/bump-version.js
scripts/preview.js

Following up on #86, this does some more general refactoring for consistency (open for discussion as always):
- Prevent variable shadowing in `scripts/build-testpage.js`, just because it is good practice.
- Use `function` rather than `const x = () => { }` for top-level functions.
- Normalize the names of variables representing errors (to `error` or `errorXyz`.
- Use only `async`/`await` and no `.then`/`.catch`.

General refactoring for consistency

---

package-lock.json
package.json

Closes #93
~~The `prepare` hook runs [on local installation](https://docs.npmjs.com/cli/v6/using-npm/scripts#life-cycle-scripts), so must be used instead of postinstall, because this is executed even installing the package from NPM.~~

Usage of 'pinst' in hooks to prevent postinstall execution during remote installation

---

README.md

Following https://github.com/simple-icons/simple-icons/pull/4716, this moves [the badges in the README](https://github.com/simple-icons/simple-icons-font/tree/ee5eeace755f219cabd020fa1a33e5c968fe2f75#status) to before the **Usage** section
For the record, I don't think this warrants releasing a patch.

Place badges before 'Usage'

---

.github/workflows/auto-release.yml

The idea is pretty simple, currently the [automated releases job](https://github.com/simple-icons/simple-icons-font/blob/18a5d4634c7405838f2c7fab610d9a0bc86a46d7/.github/workflows/auto-release.yml) will just update the simple-icons dependency and push that back to the repository. At that point the other workflows will verify that everything still works. That is fine, as we won't release anything if [the build script](https://github.com/simple-icons/simple-icons-font/blob/develop/scripts/build.js) no longer works, but it can make for an ugly commit history.
Hence, this adds one step to the automated releases job to check if the build script still works after updating simple-icons and before pushing changes.

Perform sanity check before automated releases

---

README.md
composer.json

This Pull Request is based on https://github.com/simple-icons/simple-icons/pull/1611.
This adds a `composer.json` file which, combined with [our GitHub releases](https://github.com/simple-icons/simple-icons-font/releases), will allow us to publish the font to [Packagist](https://packagist.org/) in addition to NPM similar to [the simple-icons package on Packagist](https://packagist.org/packages/simple-icons/simple-icons). The documentation in the README has also been updated to include a section on PHP usage.

Add composer.json to publish to Packagist

---

package-lock.json
package.json

Following from #105. Removes **pinst** dependency ~~and `prepublishOnly` and `postpublish` scripts from `package.json`~~.

Remove 'pinst' dependency

---

README.md

Side note: I added a "v" to the Unpkg URL for consistency with the JSDelivr URL and [these URLs in the main repository](https://github.com/simple-icons/simple-icons#cdn-usage). This is functionally equivalent to the same URL without the "v".

Update CDN urls in the README setup documentation

---

README.md

_Relates to https://github.com/simple-icons/simple-icons/pull/5736_
---
This updates the snippets in this project's documentation with the goal of making them easier to copy:
- Remove `$` from CLI snippets. It looks nice but it's included when you copy so if you paste it the command doesn't work. 
I also added the snippet type "shell" to these snippets.
- Split up the CDN example snippets so that you can copy one of them and use it, no need to have both on your website.
---
_Suggestions for other improvements are welcome, e.g. suggestions for the [Usage](https://github.com/simple-icons/simple-icons-font#usage) examples_

Make code snippets easier to copy

---

.gitignore
.npmignore
package.json

Closes #121
---
This ensures [the `DISCLAIMER.md` file of the main project](https://github.com/simple-icons/simple-icons/blob/develop/DISCLAIMER.md) is included in release of this package. This is achieved by copying it into the root of the project in the `prepublishOnly` script. Additionally, it was added to the `.npmignore` file so that it is actually published (and I also updated `.npmignore` to be more explicit & in-line with [the main project's `.npmignore`](https://github.com/simple-icons/simple-icons/blob/24ae192ef7411477231a4bcc03109a741ad691a3/.npmignore)).
I also included `DISCLAIMER.md` in this project's `.gitignore` to avoid it from ever being committed, even though the `npm run clean` command should take care of removing it after publishing.

Include DISCLAIMER.md from simple-icons in releases

---

.github/workflows/publish.yml

Add a link to the [simple-icons/simple-icons](https://github.com/simple-icons/simple-icons) release notes (i.e. GitHub release) to the GitHub releases of this font so it's easier for anyone stumbling on the GitHub releases for this project to find the changes of that version.

Improve GitHub releases

---

package.json

The same change [has been included](https://github.com/simple-icons/simple-icons/pull/6450) in simple-icons and simple-icons-pdf repositories. Note that _rimraf_ is already a dependency of other packages, so this doesn't increments `node_modules` size.

Add Windows support for `clean` script

---

scripts/templates/font.svg

This should fix the issue #113, but the patch needs to be tested by they. I've measured the remaining vertical space at the top and bottom with Inkscape to ensure that `ascent="-13"` is the correct value.

Correct vertical positioning error in font glyphs

---

README.md

Composer needs the complete name of the package to install it. Tested with composer v1 and v2.

Fix install instructions for composer package

---

.github/workflows/auto-release.yml
.github/workflows/publish.yml
.github/workflows/verify.yml

Node.js v12 is in [maintenance state and will reach his EOL in May](https://nodejs.org/en/about/releases/).

Update Node.js to v16 in CI workflows

---

.github/workflows/publish.yml

The latest version failed tagging the release. See https://github.com/simple-icons/simple-icons/issues/7339
Just drop the action and tag releases manually.

Push tag manually in 'Publish Releases' workflow

---

.github/workflows/publish.yml

Following from https://github.com/simple-icons/simple-icons/pull/7389

Upgrade `strip-gh-theme-links` action to v3

---

.github/workflows/publish.yml

Latest release [has failed](https://github.com/simple-icons/simple-icons-font/runs/6340238939?check_suite_focus=true) because I've not specified tag message creating releases in #159. If you use `set -e && EDITOR="" git tag -a "foo"` GIT exists with non-zero exit code and skips the tag creation.

Explicitly set empty tag message publishing releases

---

.gitignore
.husky/pre-commit
.npmignore
.prettierrc.js
.prettierrc.json
LICENSE.md
package-lock.json
package.json
scripts/build-testpage.js
scripts/build.js
scripts/bump-version.js
scripts/preview.js

Also includes other improvements like:
- Promisfy build script to improve performance.
- Use `npm view simple-icons --json` sys call in bump version script to improve performance if no upgrade is needed.

Convert scripts to ESM

---

.github/workflows/publish.yml
README.md

Following from https://github.com/simple-icons/simple-icons/pull/7983

Use `<picture>` blocks for GH theme images in README

---

.github/workflows/auto-release.yml

See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Update deprecated `set-output` GHA syntax

---

README.md

I noticed while browsing this repo we're still using v5 as our example version when people visit the repo.
Updated to v9 so we're keeping pace with the main repo.

Update README to use v9.

---

.github/workflows/auto-release.yml
.github/workflows/publish.yml
.github/workflows/verify.yml
README.md
package-lock.json
scripts/update-cdn-urls.js

Closes #190
Additionally, bump actions versions and use NodeJS v20 to build.

Add script to bump README CDN major versions on releases

---

.github/workflows/verify.yml

Following from https://github.com/simple-icons/simple-icons/pull/10883

Only run Verify workflow on push against develop and master branches

---

scripts/preview.js
scripts/templates/base.css

Fixes #214. See https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#setting-up-chrome-linux-sandbox
> In order to protect the host environment from untrusted web content, Chrome uses [multiple layers of sandboxing](https://chromium.googlesource.com/chromium/src/+/HEAD/docs/linux/sandboxing.md). For this to work properly, the host should be configured first. If there's no good sandbox for Chrome to use, it will crash with the error `No usable sandbox!`.
>
> If you **absolutely trust** the content you open in Chrome, you can launch Chrome with the `--no-sandbox` argument
We absolutely trust the content that we're opening as is a page created by ourselves.

No sandboxed puppeteer launch

---

preview/html/testpage.pug
scripts/build-testpage.js
scripts/build.js

The icon order is not predictable in other languages because we use JavaScript `for-in` to generate icons' Unicode.
We'd better use the same order so the developer can generate the Unicode more easily in other languages.

Keep the icon order consistent with data JSON

---

README.md
scripts/build-testpage.js
scripts/build.js

Resolves #163
- Add support for custom builds
- Use `getIconSlug()` from `simple-icons/sdk`
```shell
SI_FONT_SLUGS_FILTER=github,simpleicons npm run build
#=> github      \u{EE3B}
#=> simpleicons \u{F3FE}
```
The `SI_FONT_PRESERVE_UNICODES` is useful when users want to use only a few icons, and the Unicode doesn't change between version updates.
```shell
SI_FONT_SLUGS_FILTER=github,simpleicons SI_FONT_PRESERVE_UNICODES=false npm run build
#=> github      \u{EA01}
#=> simpleicons \u{EA02}
```

Add support for custom builds

---

.husky/pre-commit

Husky is complaining about this:
```
husky - DEPRECATED
Please remove the following two lines from .husky/pre-commit:
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
They WILL FAIL in v10.0.0
```
And use `-u` instead of `.` to only update the files affected by `npm run format`.

Remove unneeded lines in Husky pre-commit hook

---

README.md
package-lock.json
package.json
preview/assets/script.js
preview/assets/style.css
preview/html/testpage.pug
scripts/build.js
scripts/templates/base.css
scripts/templates/font.svg

Related to #222
Resolves #211
Download it from: [simple-icons-font-multi-styles.zip](https://github.com/user-attachments/files/18266580/simple-icons-font-multi-styles.zip)
- This changed the default font style to the same aspect ratio as the icon. Users still can use the squared version with the `SimpleIcons-Squared.[ext]` font file
- Re-organized the font file locations since we added a new style
- Specify the `font-style` in the font SVG template
| Before | After |
|:-:|:-:|
|![](https://github.com/user-attachments/assets/2f326721-f378-4ab8-bf04-21860ed288b2)|![](https://github.com/user-attachments/assets/6077129d-c92a-4f72-a2e2-b1b92aafab65)| 
```
font
├── simple-icons.css
├── simple-icons.min.css
├── simple-icons.json
├── simple-icons.min.json
├── SimpleIcons.eot
├── …
```

Add support for multiple font styles

---

scripts/build.js
scripts/templates/font.svg

These two font styles should not use the same font id. I've appended the style name to fix this issue.
1. Install the 15.0.0 font
```shell
brew install font-simple-icons
```
Or install the 15.0.0 builds manually on your system.
2. Open iTerm2, go to Profile - Text, change the font to Simple Icons
3. Switch font style to Regular, the Regular option cannot be selected

Fix font builds

---

README.md

Closes #213
Related to:
- https://github.com/Homebrew/homebrew-cask/pull/214483
- https://github.com/Homebrew/homebrew-cask/pull/214564

Add Homebrew setup guide

---

.github/actions/check-is-fork/action.yml
.github/workflows/auto-release.yml
.github/workflows/renovate.yml

Because permissions are missing.
Prevents things like https://github.com/mondeja/simple-icons-font/actions/runs/15899950591/job/44840339017

Don't run Auto Release nor Renovate workflows in forks

---

.gitattributes
scripts/update-cdn-urls.ts

Resolves #246
You can test this by installing the [`github-linguist`](https://github.com/github-linguist/linguist) CLI tool.
```
simple-icons-font$ github-linguist --breakdown
81.49%  16551      JavaScript
7.44%   1512       TypeScript
6.34%   1287       CSS
4.73%   960        Pug
JavaScript:
preview/assets/script.js
scripts/build-testpage.ts
scripts/build.ts
scripts/bump-version.ts
scripts/preview.ts
CSS:
preview/assets/style.css
scripts/templates/base.css
Pug:
preview/html/testpage.pug
TypeScript:
scripts/types.ts
scripts/update-cdn-urls.ts
```
```
simple-icons-font$ github-linguist --breakdown
80.64%  16395      TypeScript
8.30%   1688       JavaScript
6.33%   1287       CSS
4.72%   960        Pug
JavaScript:
preview/assets/script.js
CSS:
preview/assets/style.css …
```

Fix `github-linguist` classification of TS files as JS
